### ISSUE TITLE
How did you accomplish the exports system?

### ISSUE THREAD

**Issue by bugs181** [pinf/pinf-loader-js#29]
Hey there, just came across your repo after building something similar to this. I'm curious how you were able to create a context aware exports system. I'm having a difficult time ensuring that the module I load is the one actually setting the exports object. Are you doing this via the sandbox stuff in code?

For now, I just export a global object (that defines an exports setter) and then in the "module" files use that setter.

Pseudo code:

exporter.js:
```
Object.defineProperty(exporter, 'exports', {
  enumerable: false,
  configurable: false,

  set: function(exportFile) {
    let module = modules[exportFile.name]
    ...
    module.module = exportFile
    module.loaded = true
  },
})
```

module.js:
```
exporter.exports = {
   name: 'NameOfModule'
}
```

This works, however there isn't a 1:1 mapping of the actual file being loaded and who the module claims to be. Unless there's some sort of trickery changing the global variables or "Proxying" them so to speak. For me, this needs to work across platform so on `node` I use `global` and in browsers I use `window`.

I'd really appreciate any direction you could give.

**Comment by cadorn** [comment]
> I'm curious how you were able to create a context aware exports system.

This is the minimal code needed: https://github.com/pinf/pinf-loader-js/blob/master/loader.stripped.js

The trick is to use closures to create a local environment for each module and then map these modules onto an internal namespace. The namespace is used to link modules internally and provide external entry points.

The code I linked is pretty much as minimal as it gets to accomplish a standard yet extendable CommonJS/NodeJS module system. If you are missing pieces you likely do not go far enough in solving the problem in an abstract way.

Not sure what you are trying to do but it is all in the code above.
